### ISSUE TITLE
interchangeable textures 

### ISSUE THREAD

**Issue by MalditoInferno** [shockturtle/Patapon2HD#1]
Hey guys, I saw that the texture pack for patapon 1 had the ice shield and the patapon 2 did not, this way I knew that each new version of patapon recycles textures from the previous versions. Why are they not added to textures.ini?
![Screenshot_20210311_133703.jpg](https://user-images.githubusercontent.com/79744959/110858480-fac28e80-826e-11eb-8592-d115b986456d.jpg)

**Comment by shockturtle** [comment]
This repository doesnt use any of the textures from the remaster. They are all made by me or the people listed in the credits. That being said, I have not done the ice shield yet.
