### ISSUE TITLE
Looking to help out!

### ISSUE THREAD

**Issue by DevDreadlord** [shockturtle/Patapon2HD#4]
Hey guys @shockturtle, not sure if you're still interested in updating this project, but I am a digital artist and fan of Patapon and am willing to contribute to your project by remaking/upscaling some of the game textures in my freetime. I'm not sure how you guys go about adding them to the game via the .ini file and where you get the original textures info i.e; 000000004a4fbd2bdced6715. Anyways here is a little texture I made for the helmet the characters at the hub camp are wearing. If you wish to connect with me, i'm on twitter @DaylanRogan and discord @ Devdread#8513 if you want to DM me. 
![hlm000_0_019](https://user-images.githubusercontent.com/90724914/133326645-6a05c2ec-2fc0-4be8-a404-57ba5b6bf2ff.png)
![ball_helm](https://user-images.githubusercontent.com/90724914/133326709-8158b04d-7f72-4557-9fd2-857fefa49859.png)

**Comment by shockturtle** [comment]
Hello, considering that I sent you a friend request on discord last year around September and you never accepted it, I'll assume you don't want to help anymore. If you still want to help with the project, you can contact me on discord @ shockturtle#5038 or on twitter @shockturtle.
